# Site settings
title: "EliteMint"
description: "Upgrade to Windows 11 on unsupported hardware. Why Am I Not Losing Weight ? 8 Reasons Why, Losing Weight Ttips. Standards of Care for Individuals ages 0 to 2 years"
url: "https://elitemint.github.io"  

title_slog: "" 
title_sep: "" 
# verification
bing: "0382FBAF4E88F841A31C05DECB4AE8A0"
yandex: "553bec240e157351"
google: "PwF4hq3mVFBjsCcGrR42uglwh3O2vOvBiF3zZH3rYow"
# encoding timezone
encoding: "utf-8"
timezone: UTC
# Build settings
baseurl: / # leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:slug.html
sitemap_limit: 150.0
# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"
